
server:
  port: 0

spring:
  application:
    name: user-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: local
  datasource:
    url: jdbc:mariadb://localhost:3306/users?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to the Simple E-Commerce.


management:
  endpoints:
    web:
      exposure:
        include: busrefresh, metrics, info, prometheus
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3
jwt:
  secret: "my_secret_key_has_to_be_more_than_32Bytes_default_now"
  expire: 3600000

app:
  order-service: http://ORDER-SERVICE/order-service