server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:minkik715/ecommerse-msa-resource.git
  profiles:
    active: dev
