server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: git@github.com:minkik715/ecommerse-msa-resource.git

management:
  endpoints:
    web:
      exposure:
        include: busrefresh